name: action-zip-release

on: [push]
jobs:
  build-zip:
    name: Build and Publish Extension Zip
    runs-on: ubuntu-latest
    steps:
      - name: Checkout # 克隆项目
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Archive Release # 打包文件为 zip
        uses: thedoctor0/zip-release@master
        with:
          filename: 'DGT_Extra_datapack_Actions.zip'
          path: 'data LICENSE pack.mcmeta pack.png'

      - name: Upload Artifact #上传输出文件
        uses: actions/upload-artifact@v2
        with:
          name: action-zip-release
          path: 'DGT_Extra_datapack_Actions.zip'

      # - name: Upload Release # 发布到 Release
      #   uses: ncipollo/release-action@v1
      #   with:
      #     allowUpdates: true # 因为之前已经创建了 Release，所以要进行更新
      #     omitName: true # 更新的时候不改变 Release 的名字
      #     artifacts: 'DGT_Extra_datapack_Actions.zip' # 多个文件逗号分开
      #     token: ${{ secrets.GIT_TOKEN }} # https://github.com/settings/tokens 只选 repo 就行